[build]
builder = "nixpacks"

[deploy]
startCommand = "cd server && npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"

[environments.production.deploy]
numReplicas = 1 