[build]
builder = "nixpacks"

[deploy]
startCommand = "cd server && node index.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[environments.production.deploy]
numReplicas = 1 