services:
  - type: web
    name: dg-backend
    env: node
    plan: free
    rootDir: ./server
    buildCommand: npm ci --only=production
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production 